# Tasca M3 T01

Descripció:
Exercicis de programació numèrica.


## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [17]:
import numpy as np
import random

random_num = random.randint(1, 9)
random_dim = random.randint(2, 9)

array_ex1_dim1 = np.array(np.random.randint(100, size=(random_num)), ndmin = 1)
print("Array :", array_ex1_dim1, "amb dimensio ", array_ex1_dim1.ndim)

array_ex1_dimx = np.array([1,2,3], ndmin = random_dim)
print("Array :", array_ex1_dimx, "amb dimensio ", array_ex1_dimx.ndim)

def array_est(array):
    if array.ndim != 1:
        raise ValueError("Error, la dimensio de l'array es", array.ndim, "pero hauria d'esser 1")
    else:
        print("\nPer l'array : ", array)
        print("El nombre d'elements es: ", len(array))
        print("La suma dels elements es: ", array.sum())
        print("El minim es: ", array.min())
        print("El maxim es: ", array.max())
        print("El rang es: ", array.max() - array.min())
        print("La mitjana es: ", array.mean())
        print("Percentil 25%: ", np.percentile(array, 25))
        print("Percentil 50%: ", np.percentile(array, 50))
        print("Percentil 75%: ", np.percentile(array, 75))
        print("La mediana es: ", np.median(array))
        print("La desviacio estandar es: ", array.std())
        print("I la variança es: ", array.var())

array_est(array_ex1_dim1)
array_est(array_ex1_dimx)

Array : [22  7 46 99 71 35 70] amb dimensio  1
Array : [[[1 2 3]]] amb dimensio  3

Per l'array :  [22  7 46 99 71 35 70]
El nombre d'elements es:  7
La suma dels elements es:  350
El minim es:  7
El maxim es:  99
El rang es:  92
La mitjana es:  50.0
Percentil 25%:  28.5
Percentil 50%:  46.0
Percentil 75%:  70.5
La mediana es:  46.0
La desviacio estandar es:  29.558658388267315
I la variança es:  873.7142857142857


ValueError: ("Error, la dimensio de l'array es", 3, "pero hauria d'esser 1")

## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [19]:
def quadrat():
    random_N = random.randint(1, 9)
    arr_ex2 = np.random.randint(100, size=(random_N, random_N))
    return(arr_ex2)

print(quadrat())

[[25 29 66 52 81]
 [40 37 23 79 50]
 [48 46 64 23 44]
 [72 47 61 28 23]
 [59  7 76 48 96]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [20]:
arr_ex3 = np.random.randint(100, size=(random.randint(1, 9), random.randint(1, 9)))
print(arr_ex3)

def totals(arr):
    print("Suma per columna : ", np.sum(arr, axis=0))
    print("Suma per fila :\n", np.sum(arr, axis=1, keepdims = True))

totals(arr_ex3)

[[10 16 87 68 25 24 23]
 [86 26  0 44  2 86 62]
 [90 37 26 29 85 81 53]
 [75 62 18 54 52 41 96]
 [24 80 77 55 30  9 30]
 [85 40 90 33  8 61 10]]
Suma per columna :  [370 261 298 283 202 302 274]
Suma per fila :
 [[253]
 [306]
 [401]
 [398]
 [305]
 [327]]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [23]:
# com a exemple ens inventem unes alçades i uns pesos.
# Les alçades com a float entre 1.5 i 2. Els pesos com a integer entre 50 i 100.

heights = np.random.uniform(1.5, 2, 10)
print("Alçades (m): ", heights)
weights = np.random.randint(50, 100, 10)
print("Pesos (kg): ", weights)

# Veurem que la correlacio sempre és dolenta ja que hem creat les dades aleatoriament.
# Els coeficients de correlacio es miren a la diagonal secundaria de la matriu resultant. 

def corr_coef(arr1, arr2):
    return(np.corrcoef(arr1, arr2))

print(corr_coef(heights, weights))

Alçades (m):  [1.98115891 1.66956304 1.99795111 1.95748463 1.65533171 1.56636196
 1.96203161 1.78705564 1.58284889 1.85322552]
Pesos (kg):  [93 54 61 91 54 92 54 82 60 73]
[[1.         0.17406879]
 [0.17406879 1.        ]]


In [24]:
heights_perfect = np.random.uniform(1.5, 2, 10)
print("Alçades (m): ", heights_perfect)
weights_perfect = np.array(heights_perfect * 45)
print("Pesos (kg): ", weights_perfect)

# Ara hem forçat una correlacio molt bona, ja que hem posat 
# els pesos directament en funcio de les alçades

print(corr_coef(heights_perfect, weights_perfect))

Alçades (m):  [1.94822091 1.72789935 1.61716088 1.74382712 1.97290232 1.98051525
 1.76104382 1.80029867 1.83228995 1.73094154]
Pesos (kg):  [87.66994103 77.75547054 72.77223973 78.47222052 88.78060437 89.12318619
 79.24697168 81.01344015 82.45304771 77.8923693 ]
[[1. 1.]
 [1. 1.]]


## Resum:

El coeficient de correlacio mesura l'associacio LINEAL entre variables. Es troba entre -1 i 1. S'interpreta:  

+1 -> Correlacio completa positiva  
+0.8 -> Correlacio forta positiva  
+0.6 -> Correlacio moderada positiva  
0 -> Cap correlacio  
-0.6 -> Correlacio moderada negativa  
-0.8 -> Correlacio forta negativa  
-1 -> Correlacio completa negativa  

![imatge](https://files.realpython.com/media/py-corr-1.d13ed60a9b91.png)  

El resultat del calcul es una matriu de dos per dos.  

Els valors a la diagonal principal son iguals a 1, ja que es la correlacio entre x i x i entre y i y, que son sempre iguals.

Els valors que s'han de mirar son els de la diagonal secundaria, que son iguals i representen el 'Pearson correlation coefficient' per x i y.

## Bibliografia:

- [Stackabuse](https://stackabuse.com/calculating-pearson-correlation-coefficient-in-python-with-numpy/)
- [realpython](https://realpython.com/numpy-scipy-pandas-correlation-python/)